version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  insecure-external-code-execution: allow
  ignore:
  - dependency-name: "azure-storage-blob"
    versions: ["12.9.0"]
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
