on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]
  workflow_call: {}

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    # 5 mins for the linter run, possibly 10 min for pre-commit env reinitialization
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|py3.12|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: make setup
      - name: Run linters
        run: |
          make lint
        env:
          CI_LINT_RUN: 1

  # test-unit:
  #   name: Unit tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout commit
  #       uses: actions/checkout@v3
  #     - name: Install python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version-file: .python-version
  #         cache: pip
  #     - name: Install uv
  #       run: pip install uv
  #     - name: Install dependencies
  #       run: make setup
  #     - name: Run unit tests
  #       run: make test-unit
