NP_BUCKETS_API_K8S_NS: platform-jobs

bucketProvider: {}
#  type: "aws"  # "aws" or <not-supported-yet>
#  aws:
#    s3RoleArn:
#    accessKeyId:
#    secretAccessKey:
#    regionName:

image:
  repository: $IMAGE_REPO
  tag: $IMAGE_TAG
imagePullSecrets: []
port: 8080

replicas: 2
resources:
  requests:
    cpu: '0.1'
    memory: 300Mi
  limits:
    cpu: '0.2'
    memory: 600Mi

ingress:
  enabled: false

secrets: []

zipkin: {}

sentry: {}

annotations: {}

authUrl: http://platformauthapi:8080

platform:
  cluster_name: ""
  token: {}

corsOrigins:
enableDocs: false
