apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "platformBuckets.fullname" . }}
  namespace: {{ .Values.bucketNamespace }}
  labels: {{ include "platformBuckets.labels.standard" . | nindent 4 }}
    service: platform-buckets
rules:
- apiGroups:
  - "neuromation.io"
  resources:
  - userbuckets
  - persistentbucketcredentials
  verbs:
  - create
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "platformBuckets.fullname" . }}
  namespace: {{ .Values.bucketNamespace }}
  labels: {{ include "platformBuckets.labels.standard" . | nindent 4 }}
    service: platform-buckets
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "platformBuckets.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
