apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "platformBuckets.fullname" . }}
  namespace: {{ .Values.bucketNamespace }}
  labels: {{ include "platformBuckets.labels.standard" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - "neuromation.io"
  resources:
  - userbuckets
  - persistentbucketcredentials
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch
