apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "platformBuckets.fullname" . }}
  labels: {{ include "platformBuckets.labels.standard" . | nindent 4 }}
    platform.apolo.us/aggregate: "true"
rules:
- apiGroups:
  - "neuromation.io"
  resources:
  - userbuckets
  - persistentbucketcredentials
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
  - get
  - list
  - watch
