apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformBuckets.fullname" . }}
  labels: {{ include "platformBuckets.labels.standard" . | nindent 4 }}
    service: platform-buckets
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_BUCKETS_API_SESSION
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: tcp-web
  selector:
    app: {{ include "platformBuckets.name" . }}
    release: {{ .Release.Name }}
    service: platform-buckets
