apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformBuckets.fullname" . }}
  labels: {{ include "platformBuckets.labels.standard" . | nindent 4 }}
    service: platform-buckets
{{- with .Values.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: tcp-web
  selector:
    app: {{ include "platformBuckets.name" . }}
    release: {{ .Release.Name }}
    service: platform-buckets
