bucketProvider:
  type: "aws"  # "aws" or "minio"
  aws:
    s3RoleArn: arn:aws:iam::771188043543:role/bucker-api-users-role

annotations:
  iam.amazonaws.com/role: arn:aws:iam::771188043543:role/buckets-366c09e4841fcc83df56b8f070c34716

ingress:
  enabled: true

  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.platform.neuromation.io: "true"
    # TODO: remove traefik v1 annotations
    traefik.frontend.rule.type: PathPrefix
  hosts: [dev.neu.ro]

service:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: NEURO_BUCKETS_API_SESSION
    # TODO: remove traefik v1 annotations
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_BUCKETS_API_SESSION

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.01

platform:
  clusterName: "default"
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

bucketNamespace: platform-jobs

cors:
  origins:
    - https://neu.ro
    - https://master--neuro-web.netlify.app
    - http://localhost:8000

enableDocs: true
