bucketProvider:
  type: "aws"  # "aws" or "minio"
  aws:
    s3RoleArn: arn:aws:iam::771188043543:role/bucker-api-users-role

ingress:
  enabled: true
  ingressClassName: traefik
  hosts: [dev.neu.ro]
  annotations:
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    external-dns.platform.neuromation.io: "true"

service:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: NEURO_BUCKETS_API_SESSION

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.01

platform:
  clusterName: "default"
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: compute_token

bucketNamespace: platform-jobs


cors:
  origins:
  - '*'

enableDocs: true
