apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: persistentbucketcredentials.neuromation.io
spec:
  group: neuromation.io
  versions:
  - name: v1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              provider_name:
                type: string
              provider_type:
                type: string
              credentials:
                type: object
              bucket_ids:
                type: array
                items:
                  type: string
    additionalPrinterColumns:
    - name: PersistentBucketCredentials
      type: string
      jsonPath: .metadata.name
  scope: Namespaced
  names:
    kind: PersistentBucketCredential
    listKind: PersistentBucketCredentialsList
    plural: persistentbucketcredentials
    singular: persistentbucketcredential
    shortNames: []
