apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: userbuckets.neuromation.io
spec:
  group: neuromation.io
  versions:
  - name: v1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              provider_id:
                type: string
              provider_type:
                type: string
              created_at:
                type: string
              imported:
                type: boolean
              credentials:
                type: object
              public:
                type: boolean
              metadata:
                type: object
                nullable: true
    additionalPrinterColumns:
    - name: ProviderName
      type: string
      jsonPath: .spec.provider_name
  scope: Namespaced
  names:
    kind: UserBucket
    listKind: UserBucketsList
    plural: userbuckets
    singular: userbucket
    shortNames: []
