
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:

  name: platformbucketsapi
  annotations:

    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}

    http:
      paths:
      - path: /api/v1/buckets
        backend:
          serviceName: platformbucketsapi
          servicePort: http
      - path: /api/docs/v1/buckets
        backend:
          serviceName: platformbucketsapi
          servicePort: http

  {{- end }}
{{- end }}
