apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: userbucketscrd-admin
  namespace: {{ .Values.NP_BUCKETS_API_K8S_NS }}
rules:
- apiGroups:
  - "neuromation.io"
  resources:
  - userbuckets
  - persistentbucketcredentials
  verbs:
  - create
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: userbucketscrd-admin
  namespace: {{ .Values.NP_BUCKETS_API_K8S_NS }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: userbucketscrd-admin
  apiGroup: rbac.authorization.k8s.io
