apiVersion: v1
kind: Service
metadata:
  name: platformbucketsapi
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: NEURO_BUCKETS_API_SESSION
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: tcp-web
  selector:
    service: platformbucketsapi
