name: CI

on:
  push:
    branches: [master]
    tags: [v*.*, v*.*.*]
  pull_request:
    branches: [master]
  pull_request_target:
    branches: [master]
  schedule:
  - cron: 0 4 * * *

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: |
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    env:
      CLOUD_PROVIDER: ${{ secrets.CLOUD_PROVIDER_DEV }}
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Cache packages
      uses: actions/cache@v2.1.7
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-py-3.8.10-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('setup.cfg')
          }}
    - name: Install dependencies
      run: make setup
    - name: Install MC (minio client)
      run: |
        sudo apt-get -q update
        sudo apt-get -q install -y wget
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        sudo chmod +x mc
        sudo mv mc /usr/bin/mc
    - name: Lint
      run: |
        echo "::add-matcher::.github/actionlint-matcher.json"
        make lint
    - name: Run unit tests
      run: make test_unit
    - name: Configure AWS credentials
      if: env.CLOUD_PROVIDER == 'aws'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to AWS ECR
      if: env.CLOUD_PROVIDER == 'aws'
      uses: aws-actions/amazon-ecr-login@v1
    - name: Configure Azure credentials
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Login to Azure ACR
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_DEV_ACR_SERVER }}
        username: ${{ secrets.AZURE_DEV_ACR_USERNAME }}
        password: ${{ secrets.AZURE_DEV_ACR_PASSWORD }}
    - name: Setup minikube
      run: |
        make install_k8s
        make start_k8s
        make apply_configuration_k8s
        make test_k8s
    - name: Run integration tests
      env:
        AZURE_STORAGE_ACCOUNT_URL: ${{ secrets.AZURE_STORAGE_ACCOUNT_URL }}
        AZURE_STORAGE_CREDENTIAL: ${{ secrets.AZURE_STORAGE_CREDENTIAL }}
        GCLOUD_SA_KEY_JSON_B64: ${{ secrets.GCLOUD_SA_KEY_JSON_B64 }}
      run: make test_integration
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: .coverage-integration.xml
        flags: integration
        name: codecov-integration
    - name: Build Docker image
      run: make docker_build
      env:
        TAG: latest
    - name: Upload image artifact
      uses: neuro-inc/upload-image-action@v21.9.2
      with:
        image: platformbucketsapi
        token: ${{ secrets.GITHUB_TOKEN }}
  deploy_dev:
    name: Deploy on dev
    environment: dev
    runs-on: ubuntu-latest
    needs: test
    concurrency: deploy_dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AZURE_ACR_NAME: ${{ secrets.AZURE_DEV_ACR_NAME }}
      AZURE_REGION: ${{ secrets.AZURE_DEV_REGION }}
      AZURE_RG_NAME: ${{ secrets.AZURE_DEV_RG_NAME }}
      CLUSTER_NAME: ${{ secrets.DEV_CLUSTER_NAME }}
      HELM_ENV: dev
      CLOUD_PROVIDER: ${{ secrets.CLOUD_PROVIDER_DEV }}
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0
    - name: Configure AWS credentials
      if: env.CLOUD_PROVIDER == 'aws'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to AWS ECR
      if: env.CLOUD_PROVIDER == 'aws'
      uses: aws-actions/amazon-ecr-login@v1
    - name: Configure Azure credentials
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Login to Azure ACR
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_DEV_ACR_SERVER }}
        username: ${{ secrets.AZURE_DEV_ACR_USERNAME }}
        password: ${{ secrets.AZURE_DEV_ACR_PASSWORD }}
    - name: Set image tag
      run: echo "IMAGE_TAG=$GITHUB_SHA" >> $GITHUB_ENV
    - name: Push image to registry
      run: make docker_push
    - name: Update kube config
      run: make ${{ env.CLOUD_PROVIDER }}_k8s_login
    - name: Deploy to kubernetes
      run: make helm_deploy
