on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]
  workflow_call: {}

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    # 5 mins for the linter run, possibly 10 min for pre-commit env reinitialization
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|py3.12|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        working-directory: buckets-output-server
        run: make setup
      - name: Run linters
        working-directory: buckets-output-server
        run: |
          make lint
        env:
          CI_LINT_RUN: 1

  upload-image:
    name: Upload image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4
      - name: Build Docker image
        working-directory: buckets-output-server
        run: make build
      - name: Upload image artifact
        uses: neuro-inc/upload-image-action@v24.4.0
        with:
          image: buckets-app
          token: ${{ secrets.GITHUB_TOKEN }}
  test-unit:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
          cache: pip
      - name: Install uv
        run: pip install poetry
      - name: Install dependencies
        working-directory: buckets-output-server
        run: make setup
      - name: Run unit
        working-directory: buckets-output-server
        run: make test
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ghcr.io/neuro-inc/outputs-proxy
      #     tags: |
      #       type=ref,event=pr
      # - name: Push release for testing
      #   working-directory: buckets-output-server
      #   run: |
      #     FULL_IMAGE_NAME=${{ steps.meta.outputs.tags }}
      #     export TAG=${FULL_IMAGE_NAME##*:}
      #     make push
